sonar.projectKey=tu_org_frontend-react
sonar.organization=tu_org

# Indicamos dónde está tu código de React (normalmente src o la raíz)
# Si no usas carpeta src, cambia 'src' por '.'
sonar.sources=src
# EXCLUIMOS las carpetas nativas para que la pipeline sea rápida y barata
sonar.exclusions=android/**, ios/**, node_modules/**, build/**

# Indicamos dónde están tus tests
sonar.tests=__tests__
sonar.test.inclusions=__tests__/**/*.test.js, __tests__/**/*.test.tsx

# Reporte de cobertura para JavaScript
sonar.javascript.lcov.reportPaths=coverage/lcov.info
