name: React PR Analysis

on:
  pull_request:
    branches: [main, master, develop] # Ajusta según tu rama principal
    types: [opened, synchronize, reopened]

jobs:
  test-and-sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        # Esto genera la carpeta 'coverage' que Sonar necesita
        run: npm test -- --coverage --watchAll=false

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automático de GitHub
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # El que tú guardaste en Secrets
